### ISSUE TITLE
Special binary operation syntax in evaluate function

### ISSUE THREAD

**Issue by TheRetikGM** [FIT-IVS-segmentation-fault-core-dumped/IVS-projekt-2#2]
So lets say, we have functions such as `root`, `log`. Both of these functions have two variants for special parameters: `sqrt` and `ln`. The question is, how should be pass these into the evaluate string? 

I am considering this:
- For the special cases:  `evaluate("sqrt(<NUM>)")`, `evaluate("ln(<NUM>)")`
- For the generic cases: 
    - a) `evaluate("<N>root<NUM>")` , `evaluate("<A>log<NUM>")`
    - b) `evaluate("root(<N>, <NUM>)"`, `evaluate("log(<A>, <NUM>)")`
 
I like the `a` variant, because it would be much easier to write expressions with it, however it could have a problem with expressions such as `evaluate("(4+5)root(2log4)")`, where the `b` variant would handle it like this: `evaluate("root(4+5, log(2, 4))")`. Also in the `a` variant it would be easier to type undefined expressions like `4+5root2log4`.  

What do you think about this?

**Comment by tmokenc** [comment]
I think the `b` variable would make more sense both mathematically and programmatically.
The `root` and `log` are already defined as mathematic functions, not operators like `add/sub/mul/div/pow/mod`.
According to [this Wikipedia page](https://en.wikipedia.org/wiki/Function_(mathematics)#Functional_notation), the most common way for denoting functions is the functional notation, which has form `f(x)`, where `f` is the name of the function and `x` is its parameter(s), in this case, it's exactly the `b` variant.

**Comment by Blazeo7** [comment]
Honestly, I would go for the `a` variant, because it is much more intuitive and user friendly option,
but if those expressions are already defined as a function `f(a, b)`, then I wouldn't change it.

**Comment by TheRetikGM** [comment]
Well, then we could go for both. In the display part we could use the  `a` variant and in the evaluation string we would use the `b` variant.

**Comment by tmokenc** [comment]
I personally want to stick with the `b` one, because the `a` variant has serveral problems
-  `<N>root<M>` and be think as `<N> * root<M>`
- Nested function can be problematic as @TheRetikGM have mentioned
- The `log` function is confusing, because the right notation for it is `log<N><M>`. In mathematics `<N>log<M>` is equal to `log10(M^N)`

There are some advantages to using the a variant when it comes to implementing the cursor.
I think this problem is just for us developer, since user shouldn't be able to use the inner `evaluate` function directly.
I think we can implement the `b` variant first because it is *a lot* easier to implement and it's hard for things to go wrong. We can add support for the `a` variant later, like if a function takes in n-1 arguments, it will take the number defined before it

**Comment by TheRetikGM** [comment]
Indeed. The evaluation function should use the `b` variant. How it will be displayed to the user and how exactly it will be created by the user is a separate issue.
